### ISSUE TITLE
Nemo 2.8.7 received signal SIGSEGV, Segmentation fault (add_extension_menu_items -> at nemo-view.c:5630)

### ISSUE THREAD

**Issue by hotice** [linuxmint/nemo#1116]
Nemo 2.8.7 (and previous 2.8.x versions) crashes often, although not always, when using multiple tabs with large directories. To replicate this behavior (but again: it doesn't occur every single time): open a large folder (let's say Downloads), then enter a subfolder and quickly open that large folder again in a new tab (if it's the Downloads folder, you can open it from the sidebar).

From what I can tell (though I'm not a developer) is that this occurs due to the expandable/collapsible context menu introduced fairly recently.

Tested with Nemo without any patches.

Here's the debug log:
```
andrei@andrei-desktop:~$ gdb /usr/bin/nemo
GNU gdb (Ubuntu 7.11-0ubuntu1) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/nemo...Reading symbols from /usr/lib/debug//usr/bin/nemo...done.
done.
(gdb) run
Starting program: /usr/bin/nemo 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffec45f700 (LWP 7691)]
[New Thread 0x7fffebc5e700 (LWP 7692)]
[New Thread 0x7fffeb45d700 (LWP 7693)]
[New Thread 0x7fffe9775700 (LWP 7694)]
sys:1: PyGIWarning: Nemo was imported without specifying a version first. Use gi.require_version('Nemo', '3.0') before import to ensure that the right version gets loaded.
/usr/share/nemo-python/extensions/periscope-nemo.py:31: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
[Errno 2] No translation file found for domain: 'nemo-copypaste-images'
[Nemo Terminal] I: Initializing the Nemo extension
Initializing nemo-dropbox 2.2.0
[New Thread 0x7fffd961e700 (LWP 7697)]
Initializing nemo-image-converter extension
[New Thread 0x7fffcfc5a700 (LWP 7699)]
[New Thread 0x7fffcedf4700 (LWP 7700)]
[New Thread 0x7fffce5f3700 (LWP 7701)]

** (nemo:7687): CRITICAL **: nemo_menu_provider_get_background_items: assertion 'NEMO_IS_MENU_PROVIDER (provider)' failed
[New Thread 0x7fffcc9d3700 (LWP 7717)]

** (nemo:7687): CRITICAL **: nemo_menu_provider_get_background_items: assertion 'NEMO_IS_MENU_PROVIDER (provider)' failed
[Thread 0x7fffcc9d3700 (LWP 7717) exited]
[Thread 0x7fffcedf4700 (LWP 7700) exited]
[Thread 0x7fffce5f3700 (LWP 7701) exited]
[Thread 0x7fffe9775700 (LWP 7694) exited]
sys:1: PyGIWarning: Nemo was imported without specifying a version first. Use gi.require_version('Nemo', '3.0') before import to ensure that the right version gets loaded.
/usr/share/nemo-python/extensions/periscope-nemo.py:31: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify

** (nemo:7687): CRITICAL **: nemo_menu_provider_get_background_items: assertion 'NEMO_IS_MENU_PROVIDER (provider)' failed
[New Thread 0x7fffe9775700 (LWP 7727)]
[New Thread 0x7fffce5f3700 (LWP 7728)]
[Thread 0x7fffce5f3700 (LWP 7728) exited]
[Thread 0x7fffcfc5a700 (LWP 7699) exited]
[New Thread 0x7fffcfc5a700 (LWP 7729)]
[Thread 0x7fffcfc5a700 (LWP 7729) exited]

** (nemo:7687): CRITICAL **: nemo_menu_provider_get_background_items: assertion 'NEMO_IS_MENU_PROVIDER (provider)' failed
[New Thread 0x7fffcfc5a700 (LWP 7739)]
[New Thread 0x7fffce5f3700 (LWP 7740)]

** (nemo:7687): CRITICAL **: nemo_menu_provider_get_background_items: assertion 'NEMO_IS_MENU_PROVIDER (provider)' failed

(nemo:7687): Gtk-CRITICAL **: gtk_action_group_get_action: assertion 'GTK_IS_ACTION_GROUP (action_group)' failed

(nemo:7687): Gtk-CRITICAL **: gtk_action_group_add_action: assertion 'GTK_IS_ACTION_GROUP (action_group)' failed

Thread 1 "nemo" received signal SIGSEGV, Segmentation fault.
add_extension_menu_items (view=view@entry=0x122e980 [NemoIconView], files=files@entry=0x0, menu_items=menu_items@entry=0x2257ae0, subdirectory=subdirectory@entry=0x563214 "")
    at nemo-view.c:5630
5630	            if (G_OBJECT_TYPE (action) == NEMO_TYPE_SEPARATOR_ACTION)
(gdb) thread apply all bt

Thread 15 (Thread 0x7fffce5f3700 (LWP 7740)):
#0  0x00007ffff3fff6d9 in syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff4dfbcaa in g_cond_wait_until (cond=cond@entry=0x7fffe400e308, mutex=mutex@entry=0x7fffe400e300, end_time=end_time@entry=180738392376)
    at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gthread-posix.c:1444
#2  0x00007ffff4d8b929 in g_async_queue_pop_intern_unlocked (queue=0x7fffe400e300, wait=wait@entry=1, end_time=180738392376)
    at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gasyncqueue.c:422
#3  0x00007ffff4d8bf88 in g_async_queue_timeout_pop_unlocked (queue=<optimized out>, timeout=timeout@entry=500000) at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gasyncqueue.c:570
#4  0x00007ffff4dde4d6 in g_thread_pool_thread_proxy (pool=0x7fffe400e2a0) at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gthreadpool.c:262
#5  0x00007ffff4dde4d6 in g_thread_pool_thread_proxy (data=<optimized out>) at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gthreadpool.c:296
#6  0x00007ffff4dddb65 in g_thread_proxy (data=0x11a6000) at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gthread.c:780
#7  0x00007ffff42cf66a in start_thread (arg=0x7fffce5f3700) at pthread_create.c:333
#8  0x00007ffff400501d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 14 (Thread 0x7fffcfc5a700 (LWP 7739)):
#0  0x00007ffff3fff6d9 in syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff4dfbcaa in g_cond_wait_until (cond=cond@entry=0x7fffe400e308, mutex=mutex@entry=0x7fffe400e300, end_time=end_time@entry=180738391857)
    at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gthread-posix.c:1444
#2  0x00007ffff4d8b929 in g_async_queue_pop_intern_unlocked (queue=0x7fffe400e300, wait=wait@entry=1, end_time=180738391857)
    at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gasyncqueue.c:422
#3  0x00007ffff4d8bf88 in g_async_queue_timeout_pop_unlocked (queue=<optimized out>, timeout=timeout@entry=500000) at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gasyncqueue.c:570
#4  0x00007ffff4dde4d6 in g_thread_pool_thread_proxy (pool=0x7fffe400e2a0) at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gthreadpool.c:262
#5  0x00007ffff4dde4d6 in g_thread_pool_thread_proxy (data=<optimized out>) at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gthreadpool.c:296
#6  0x00007ffff4dddb65 in g_thread_proxy (data=0x33b7e30) at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gthread.c:780
#7  0x00007ffff42cf66a in start_thread (arg=0x7fffcfc5a700) at pthread_create.c:333
#8  0x00007ffff400501d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 11 (Thread 0x7fffe9775700 (LWP 7727)):
#0  0x00007ffff3fff6d9 in syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff4dfbcaa in g_cond_wait_until (cond=cond@entry=0x7fffe400e308, mutex=mutex@entry=0x7fffe400e300, end_time=end_time@entry=180738402303)
    at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gthread-posix.c:1444
---Type <return> to continue, or q <return> to quit---
#2  0x00007ffff4d8b929 in g_async_queue_pop_intern_unlocked (queue=0x7fffe400e300, wait=wait@entry=1, end_time=180738402303)
    at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gasyncqueue.c:422
#3  0x00007ffff4d8bf88 in g_async_queue_timeout_pop_unlocked (queue=<optimized out>, timeout=timeout@entry=500000) at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gasyncqueue.c:570
#4  0x00007ffff4dde4d6 in g_thread_pool_thread_proxy (pool=0x7fffe400e2a0) at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gthreadpool.c:262
#5  0x00007ffff4dde4d6 in g_thread_pool_thread_proxy (data=<optimized out>) at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gthreadpool.c:296
#6  0x00007ffff4dddb65 in g_thread_proxy (data=0x1633450) at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gthread.c:780
#7  0x00007ffff42cf66a in start_thread (arg=0x7fffe9775700) at pthread_create.c:333
#8  0x00007ffff400501d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 6 (Thread 0x7fffd961e700 (LWP 7697)):
#0  0x00007ffff3fff6d9 in syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff4dfbcaa in g_cond_wait_until (cond=cond@entry=0xf51338, mutex=mutex@entry=0xf51330, end_time=end_time@entry=180738015781)
    at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gthread-posix.c:1444
#2  0x00007ffff4d8b929 in g_async_queue_pop_intern_unlocked (queue=queue@entry=0xf51330, wait=wait@entry=1, end_time=end_time@entry=180738015781)
    at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gasyncqueue.c:422
#3  0x00007ffff4d8bfe9 in g_async_queue_timed_pop (queue=0xf51330, end_time=0x7fffd961dac0) at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gasyncqueue.c:609
#4  0x00007fffd962570b in  () at /usr/lib/nemo/extensions-3.0/libnemo-dropbox.so
#5  0x00007ffff4dddb65 in g_thread_proxy (data=0xf60000) at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gthread.c:780
#6  0x00007ffff42cf66a in start_thread (arg=0x7fffd961e700) at pthread_create.c:333
#7  0x00007ffff400501d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 4 (Thread 0x7fffeb45d700 (LWP 7693)):
#0  0x00007ffff3ff99ed in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff4db731c in g_main_context_iterate (priority=2147483647, n_fds=5, fds=0x7fffe0001190, timeout=<optimized out>, context=0x7fffe40134c0)
    at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gmain.c:4135
#2  0x00007ffff4db731c in g_main_context_iterate (context=0x7fffe40134c0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gmain.c:3835
#3  0x00007ffff4db76a2 in g_main_loop_run (loop=0x7fffe4013450) at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gmain.c:4034
#4  0x00007ffff53b5816 in gdbus_shared_thread_func (user_data=0x7fffe4013490) at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./gio/gdbusprivate.c:246
#5  0x00007ffff4dddb65 in g_thread_proxy (data=0x7ff320) at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gthread.c:780
#6  0x00007ffff42cf66a in start_thread (arg=0x7fffeb45d700) at pthread_create.c:333
---Type <return> to continue, or q <return> to quit---
#7  0x00007ffff400501d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 3 (Thread 0x7fffebc5e700 (LWP 7692)):
#0  0x00007ffff3ff99ed in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff4db731c in g_main_context_iterate (priority=2147483647, n_fds=2, fds=0x7fffdc0008c0, timeout=<optimized out>, context=0x7fffe400e440)
    at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gmain.c:4135
#2  0x00007ffff4db731c in g_main_context_iterate (context=context@entry=0x7fffe400e440, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gmain.c:3835
#3  0x00007ffff4db742c in g_main_context_iteration (context=0x7fffe400e440, may_block=may_block@entry=1) at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gmain.c:3901
#4  0x00007ffff4db7469 in glib_worker_main (data=<optimized out>) at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gmain.c:5672
#5  0x00007ffff4dddb65 in g_thread_proxy (data=0x7ff2d0) at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gthread.c:780
#6  0x00007ffff42cf66a in start_thread (arg=0x7fffebc5e700) at pthread_create.c:333
#7  0x00007ffff400501d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7fffec45f700 (LWP 7691)):
#0  0x00007ffff3ff99ed in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff4db731c in g_main_context_iterate (priority=2147483647, n_fds=1, fds=0x7fffe40010c0, timeout=<optimized out>, context=0x8357b0)
    at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gmain.c:4135
#2  0x00007ffff4db731c in g_main_context_iterate (context=context@entry=0x8357b0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gmain.c:3835
#3  0x00007ffff4db742c in g_main_context_iteration (context=0x8357b0, may_block=1) at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gmain.c:3901
#4  0x00007fffec46728d in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
#5  0x00007ffff4dddb65 in g_thread_proxy (data=0x7fed90) at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gthread.c:780
#6  0x00007ffff42cf66a in start_thread (arg=0x7fffec45f700) at pthread_create.c:333
#7  0x00007ffff400501d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7ffff7f13a40 (LWP 7687)):
#0  0x0000000000495aad in add_extension_menu_items (view=view@entry=0x122e980 [NemoIconView], files=files@entry=0x0, menu_items=menu_items@entry=0x2257ae0, subdirectory=subdirectory@entry=0x563214 "") at nemo-view.c:5630
#1  0x00000000004a61d8 in real_update_menus (selection=0x0, view=0x122e980 [NemoIconView]) at nemo-view.c:5696
#2  0x00000000004a61d8 in real_update_menus (view=0x122e980 [NemoIconView]) at nemo-view.c:9691
---Type <return> to continue, or q <return> to quit---
#3  0x0000000000449db0 in nemo_icon_view_update_menus (view=0x122e980 [NemoIconView]) at nemo-icon-view.c:1569
#4  0x000000000049ea9f in update_menus_timeout_callback (view=0x122e980 [NemoIconView]) at nemo-view.c:804
#5  0x000000000049ea9f in update_menus_timeout_callback (data=<error reading variable: value has been optimized out>) at nemo-view.c:3812
#6  0x00007ffff4db7a43 in g_timeout_dispatch (source=0x44ea3d0, callback=<optimized out>, user_data=<optimized out>) at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gmain.c:4577
#7  0x00007ffff4db6fda in g_main_context_dispatch (context=0x7f4c00) at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gmain.c:3154
#8  0x00007ffff4db6fda in g_main_context_dispatch (context=context@entry=0x7f4c00) at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gmain.c:3769
#9  0x00007ffff4db7380 in g_main_context_iterate (context=context@entry=0x7f4c00, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gmain.c:3840
#10 0x00007ffff4db742c in g_main_context_iteration (context=context@entry=0x7f4c00, may_block=may_block@entry=1) at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./glib/gmain.c:3901
#11 0x00007ffff537ebcd in g_application_run (application=0x7fa130 [NemoApplication], argc=argc@entry=1, argv=argv@entry=0x7fffffffdd48)
    at /build/glib2.0-SNH0tt/glib2.0-2.47.6/./gio/gapplication.c:2363
#12 0x0000000000430d56 in main (argc=1, argv=0x7fffffffdd48) at nemo-main.c:106
(gdb) 
```

**Comment by mtwebster** [comment]
Can you disable all extensions temporarily and try to reproduce?  You can do this from the Plugins window (Edit menu, by Preferences) - you'll need to restart nemo after disabling/re-enabling.

The issues with context menu toggle should be fixed in 2.8.7, I suspect an extension right now perhaps.

Thanks

**Comment by hotice** [comment]
I think it might be an extension, though not the extension itself but the fact that it creates a context menu entry. So I'm guessing this won't happen with 0 extensions that don't add a context menu entry. Either way, I'll give it a try and let you know.

**Comment by hotice** [comment]
Well, it didn't crash with 0 extensions enabled. But they I re-enabled all extensions and it still doesn't crash. If only it was reproducible every time... because it did crash about 10 times for me today. I'll keep trying and let you know.

**Comment by keitalbame** [comment]
For me always crashes when I change the size of the name column and open a new tab, using it as reference, like I mention [here](https://github.com/linuxmint/nemo/issues/984#issuecomment-174961916).

**Comment by hotice** [comment]
Well I've managed to find another bug while testing this.

Steps to reproduce:
have a folder ~/Downloads/test which has a subfolder ~/Downloads/test/testsubfolder
1. Open "Downloads" from the sidebar (I've used this folder because it has lots of files), then quickly middle click Downloads from the sidebar again, so it also opens in a new tab
2. on the second Downloads tab, middle click "testsubfolder" so it opens in a new tab
3. switch to the "testsubfolder" tab
4. in the "testsubfolder" tab, right click and select "Create new document > Empty document".

the result varies:
sometimes nemo just crashes
sometimes the new empty document is created under ~/Downloads/test, and not as it should be, under ~/Downloads/test/testsubfolder
most of the times the file is created under ~/Downloads, instead of ~/Downloads/test/testsubfolder

This last case happens most of the time and there's nothing in the debug log about it.

Tested with 0 extensions enabled.

**Comment by hotice** [comment]
@keitalbame you mean in the list view, if you resize the name column and then use middle click to open one of the folders from the list? I just tried it and for me, in 90% of cases middle clicking a folder in list view does absolutely nothing. So another bug I guess...

**Comment by keitalbame** [comment]
I'm not using the middle click (more a keyboard user) but doing a CTRL+T on a folder, will open that folder on a new tab.
If I changed the name column size, it will immediatly close nemo while CTRL+T.

Maybe middle click have a different behaviour while on list view.
Can't test at the moment.

Which distro/version are you using?

**Comment by hotice** [comment]
I edited my comment. It's that middle click thingy I was talking about is not a bug, it requires double middle click apparently.

**Comment by hotice** [comment]
It appears that indeed this bug was caused by an extension so I'm closing it and I'll open a new one for the other bug I mentioned.
