### ISSUE TITLE
(Un)selecting columns doesn't work correctly

### ISSUE THREAD

**Issue by jf99** [linuxmint/nemo#1190]
Watch the video:
[nemo-bug.zip](https://github.com/linuxmint/nemo/files/287681/nemo-bug.zip)

Also notice the many Gtk-warnings in the console output window. This should be the same as #1153.
At 0:07 you can also see #1173.

**Comment by itzexor** [comment]
This should be fixed since 3.0.1

**Comment by jf99** [comment]
Negative. The video has been recorded with nemo 3.0.3 and it still happens with 3.0.5. Next time I make a video, I should show the "about"-window.

**Comment by itzexor** [comment]
Alright, I'll have a look at it later today and see if i can figure that out.

**Comment by itzexor** [comment]
I've not tracked down the exact cause of this issue yet, but I've found that enabling the Preferences->Behavior->Ignore per-folder view preferences option causes it to work properly.

I know this isn't a solution, and I'm still working on tracking it down, but in the meantime if you need this functionality to work properly there's a workaround.

**Comment by jf99** [comment]
Thanks for investigating. I can confirm that. Per-folder view preferences are more important for me, though.

**Comment by itzexor** [comment]
This should now be fixed as @mtwebster has done some work on it and pushed it as:
https://github.com/linuxmint/nemo/commit/f81d139d8e640ce682d69772bafd091e10402a62
https://github.com/linuxmint/nemo/commit/519d8dda53620458d263ce4b8f1de159a63fc588
https://github.com/linuxmint/nemo/commit/93fa16e066e90cd389f166707169c46af20a7527

**Comment by jf99** [comment]
This is indeed fixed in nemo 3.0.6.
