### ISSUE TITLE
Escape and space freeze nemo preview instead of closing it

### ISSUE THREAD

**Issue by ManuelSchneid3r** [linuxmint/nemo#1206]
Archlinux so upstream version. Hitting space shows preview. Fine, but hitting space or escape again lets the content dissapear and the window being transparent. The window stays and does not react anymore. After multiple presses I get the offer to force quit the previewer. This does **not** happen when pressing the close button or Alt+F4. 

![image](https://cloud.githubusercontent.com/assets/3252315/16098594/1eb15f70-3354-11e6-9405-870b2ce092bd.png)

**Comment by mtwebster** [comment]
This is fixed in the latest nemo-preview I think, see https://github.com/linuxmint/nemo-extensions/compare/7bb92f6b56b3d990c759351b81fd6bb369b9729e...65f0f87796bb9ea81140395454b3785579219707

It looks like arch still has just 2.8, there is a 3.0.2 now, maybe ping the maintainer.

**Comment by ManuelSchneid3r** [comment]
Haha i'm slightly disillusionated :D Pardon me, I never stumbled upon a package in the official repos that is that outdated.

**Comment by ManuelSchneid3r** [comment]
I cant find out if this commit is past 3.0.0. This is still a problem with latest release. (3.0.0)

**Comment by mtwebster** [comment]
It's the clutter-gst3.patch file here: https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/nemo-extensions and it's being applied.. I'm not sure why the problem remains, I'll try it out when I get a chance - I have an arch vm I haven't managed to ruin yet.
