### ISSUE TITLE
There are several desktop icon bugs that were introduced in Linux Mint 18.3

### ISSUE THREAD

**Issue by cdgoldin** [linuxmint/nemo#1674]
* Nemo version = 3.6.5
* The issue is with the cinnamon desktop (but the cinnamon people claim desktop management is a nemo problem)
* Distribution = Linux Mint 18.3 cinnamon
* Graphics hardware *and* driver used are totally irrelevant to the problem reported.
* 64 bit

**Issue**

There are several desktop icon bugs that were introduced in Linux Mint 18.3

1) Some of the system icons (i.e. computer, home, network, trash and mounted volumes) are overlaid on top of each other when you reboot or log-on.

2) Pressing F5 (which is supposed to refresh the desktop) causes more of them to be overlaid on top of each other, until they all share the single icon position at the top left of the screen.

3) Saving a (new) file to the desktop, which used to create an icon in the first OPEN position (left-to-right, top-to-bottom), now overlays the first icon before the open position.

4) "Align to grid" now aligns to a much more compact grid, which is far less readable because it crams the icon descriptions into the icon images.

Items 1-4 only occur in Linux Mint 18.3 cinnamon (nemo), not mate (caja)

**Steps to reproduce**

1) Reboot or login to Linux Mint 18.3 cinnamon and observe
2) Press F5 and observe
3) Check "align to grid" and observe

**Expected behaviour**
I would expect the desktop to behave as it did with previous releases, and NOT overlay icons on top of each other, nor compress the desktop illegibly with "align to grid".

**Other information**
The last time I reported a desktop problem on "gitgub", I was told to move it to nemo (without providing a link to do so), even though it was a problem that only occurred with cinnamon. So I am reporting it now to both groups, in hopes that someone will address the problem. It's very disappointing that a new release would contain such obvious problems.

Before rebooting or re-logging in:
![screenshot before rebooting or re-login](https://user-images.githubusercontent.com/31964441/34273097-3007f45e-e650-11e7-926f-63c9b701c695.gif)

After rebooting or re-logging in (should be same as above, but isn't):
![screenshot after login should be the same as before login](https://user-images.githubusercontent.com/31964441/34273094-2fcf5f90-e650-11e7-8c4c-c61f2dfac18c.gif)

5) The same problem described in item #3 above occurs when a device is mounted, i.e. the desktop icon for the device overlays the last "system" icon on the desktop (usually the bottom of the leftmost column).

After mounting device:
![screenshot after mounting device](https://user-images.githubusercontent.com/31964441/34273095-2fe409e0-e650-11e7-830c-9bab63bda9a4.gif)

Should be:
![screenshot as it should be after mounting device](https://user-images.githubusercontent.com/31964441/34273096-2ff57d42-e650-11e7-9f26-3550177f31d3.gif)

**Comment by cdgoldin** [comment]
The same problem described in item #3 above occurs when a device is mounted, i.e. the desktop icon for the device overlays the last "system" icon on the desktop (usually the bottom of the leftmost column).

**Comment by dodona2** [comment]
Some of the system icons aren' overlaid on top of each other when you log-on, but at the wrong location. This started with Fedora 26 and is still there in Fedora 27.. See:
![screenshot from 2017-12-20 12-02-04](https://user-images.githubusercontent.com/16303732/34204296-5dee19ca-e57e-11e7-91e1-9a7cab3dae62.png)
this is how it ought to be:
![screenshot from 2017-12-20 12-02-35](https://user-images.githubusercontent.com/16303732/34204317-70bf2a1c-e57e-11e7-96be-469d2c2e1400.png)

**Comment by mtwebster** [comment]
For the original issue, please see: https://github.com/linuxmint/nemo/issues/1654#issuecomment-356261713

@dodona2 is that with nemo 3.6.5?

**Comment by cdgoldin** [comment]
1) I read through #1654. It is a similar problem, but I'm not sure it's identical. Are you suggesting we try the solution described in the message beginning "Mind trying these packages before I get a new release out:"?

2) I'm fairly certain it's nemo 3.6.5, as stated in my "bug report", but don't remember how to check the nemo version to verify this.

----- Original Message -----

**Comment by JosephMcc** [comment]
I remember having some of these issues but I don't get them any more with Nemo 3.8. Can the rest of you still reproduce this?

**Comment by cdgoldin** [comment]
Most (not all) of "these issues" were "solved" by replacing cinnamon-nemo 3.6.5+sylvia with about 10 program modules, none of which have been issued as official updates. (See 
https://bugs.launchpad.net/linuxmint/+bug/1738302 and https://github.com/linuxmint/nemo/issues/1654). I have no idea how to determine the current Nemo version (and there is nothing on the Internet that provides this information), but I'm unaware of any new Nemo version being made available by the Mint Update program (which still shows cinnamon-nemo 3.6.5+sylvia as a pending update (as a result of the aforementioned patches)).

----- Original Message -----

**Comment by ChooChooAl** [comment]
I was just going to report this same issue in 18.3 with nemo 3.6.5.
I have a copy of 19 and it's running nemo 3.8 and I cannot reproduce the issue there.
I've tried a lot of variations of desktop icon alignment with no luck on mint 18.3.   See attached file.  Same as author, any of the desktop icons in settings overlap or any mounted volume / thumb drive etc.
![desktop icons overlapping](https://user-images.githubusercontent.com/26556059/44374136-c6253680-a4ba-11e8-860f-03195472735b.png)

**Comment by cdgoldin** [comment]
In #1654, mtwebster said ""Mind trying these packages before I get a new release out:?" which implies that he was/is waiting for the next Linux Mint release before implementing the 10 patched modules. If Mint 19 is available, presumably the patched modules were incorporated. However, item #4 ("Align to grid" now aligns to a much more compact grid, which is far less readable because it crams the icon descriptions into the icon images) has NOT been addressed to my knowledge.
Where did you find Mint 19? Update Manager doesn't show it.

**Comment by ChooChooAl** [comment]
Linux mint 19 I got off of https://linuxmint.com/.   Virgin load not upgrade.  I'm testing it in a VM.
I too have noticed the grid being odd but have found that it can be adjusted in dconf editor.   And since I can adjust it via standard tools, I consider it a non issue, more of a feature request for the grid default to be a bit more reasonable size.   I think my grid issue was that it was way too large though.   Maybe it's a screen size / dpi / video card issue.   I don't know enough about all that, just it was large spacing.
In 18.3, Dconf Editor -> org->nemo->desktop->horizontal grid adjust set to 0.80000000000000004441
And obviously .8 means I shrunk down the spacing.

**Comment by CottonEaster** [comment]
I think at least some of the problems reported here have been fixed.

**Comment by johnstrasser** [comment]
Sorry to re-raise an old thread...

Still an issue with LM 19.2 and 19.3.  I don't remember if I saw it on LMDE 3 and have not yet tried LMDE4
===> Some of the system icons (i.e. computer, home, network, trash and mounted volumes) are overlaid on top of each other when you reboot or log-on.

Is there a config file somewhere where desktop icon info is stored?

**Comment by xenopeek** [comment]
I can't reproduce this with Nemo 4.6.4 on Linux Mint 20 Cinnamon. Either with auto-arrange on or off, and boot resolution being smaller than resolution after log in, the icons are shown in the same location as before reboot.
