### ISSUE TITLE
.txt files hang nemo when copied over Samba

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/nemo#1683]
```
 * Nemo version (nemo --version) 3.6.5
 * Is issue with desktop or windowed nemo? Both
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * 32 or 64 bit: 64
 ```

I have some Windows paths connected to Mint via Samba. I can copy files from Windows to Mint using those paths (/shares) - except text files, and whether or not those text files have a .txt extension. When I attempt that Windows-Mint copy of text files, I see

![image](https://user-images.githubusercontent.com/9998846/34500630-7f8e17d0-f003-11e7-98d7-18980326c9a9.png)

and the copy never completes and indeed - perhaps only when I am trying to copy multiple files at once - it is hard to get rid of the stalled window.

Copying files from Mint *to* Windows, including text files, works unproblematically.

Possibly my fstab - which I could reproduce, and which contains my share details - is at fault, but even if so I think nemo should fail more gracefully.

**Steps to reproduce**

Create or locate a text file on Mint. Try to copy it to a Windows computer using Samba.

**Expected behaviour**

The file(s) should copy or, if there is SAMBA or fstab config problem, I should get some sort of error message.

**Other information**

Firewalls do not seem to the problem.

I have a VPN on both computers, but disabling the VPNs did not solve the problem

**Comment by CottonEaster** [comment]
The problem might be with gvfs, and related to the one described here: https://bugs.launchpad.net/ubuntu/+source/gvfs/+bug/1075923

**Comment by CottonEaster** [comment]
The problem tends to produce this:

![image](https://user-images.githubusercontent.com/9998846/34504556-23e011fe-f017-11e7-950a-95c202b86536.png)

and those little file icons are hard - too hard - to make go away. I had to restart Cinnamon.

**Comment by mp-smith** [comment]
I'm experiencing a very similar problem when I copy a large number of files (any type) with Nemo.

Using Fedora 27, Gnome 3.26.2 and Nemo 3.6.5. 
Copying large numbers of files with Nemo from a CentOS7 Samba server to the F27 SSD freezes. 
I recently switched from F24 to F27. I Never had a problem with Nemo in F24 (same Samba server).
+ Problem is always and easily repeatable.
+ Only the process doing the copy freezes.
  - closing the copy progress window leaves the process running in the background.
  - any subsequent Nemo file copy operations queue behind the frozen process.
  - logging out and back into GNOME clears the frozen process.
+ similar file copy operations via Nemo from external USB HDD to F27 SSD works fine.
+ similar file copy operations via cp(1) and rsync(1) with ksh(1) from Samba server to F27 SSD works fine.
+ copying one file using Nemo from Samba server to F27 SSD works fine.

**Comment by severach** [comment]
More data points running Manjaro Cinnamon.

````
# pacman -Q cinnamon nemo
cinnamon 3.6.7-2
nemo 3.6.5-1
````

Folder is mounted with autofs

* Hangs with Nemo running under Cinnamon
* Hangs with Thunar running under Cinnamon
* Hangs with Nautilus running under Cinnamon
* Hangs with Thunar running under XFCE
* Hangs with local mount ro or rw
* Hangs with gvfs forcibly uninstalled (`pacman -Rdd gvfs`)
* Hangs after rename user folder and create new one
* Under Cinnamon another copy hangs immediately behind the first
* Under XFCE another copy starts and hangs part way through as did the first
* If the transfer hangs too quickly the progress dialog is never shown.
* Hangs with Samba client 4.7.4 4.7.0 4.6.7 4.6.0
* Hangs with Kernel 4.15.1 4.14.17
* Hangs with Windows or Samba share
* Perform the copy again and it hangs on the exact same file. The second time goes much faster since the files and folders are in the disk cache.

When hung we see this. When you look in htop these all say nemo.

````
# lsof | grep mnt
nemo      10689                  chris   17r      DIR               0,43         0   14155894 /mnt/WINDVR
nemo      10689                  chris   18r      REG               0,43       155   14158143 /mnt/WINDVR/FTP Site.URL
gmain     10689 10691            chris   17r      DIR               0,43         0   14155894 /mnt/WINDVR
gmain     10689 10691            chris   18r      REG               0,43       155   14158143 /mnt/WINDVR/FTP Site.URL
gdbus     10689 10692            chris   17r      DIR               0,43         0   14155894 /mnt/WINDVR
gdbus     10689 10692            chris   18r      REG               0,43       155   14158143 /mnt/WINDVR/FTP Site.URL
dconf\x20 10689 10701            chris   17r      DIR               0,43         0   14155894 /mnt/WINDVR
dconf\x20 10689 10701            chris   18r      REG               0,43       155   14158143 /mnt/WINDVR/FTP Site.URL
pool      10689 10772            chris   17r      DIR               0,43         0   14155894 /mnt/WINDVR
pool      10689 10772            chris   18r      REG               0,43       155   14158143 /mnt/WINDVR/FTP Site.URL
# kill 10772
# lsof | grep mnt
# 
````

Attaching strace to each process shows no kernel activity except for nemo. 

````
# strace -p 10689
strace: Process 10689 attached
restart_syscall(<... resuming interrupted poll ...>) = 0
inotify_add_watch(11, "", IN_MODIFY|IN_ATTRIB|IN_CLOSE_WRITE|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE|IN_DELETE_SELF|IN_MOVE_SELF|IN_UNMOUNT|IN_ONLYDIR) = -1 ENOENT (No such file or directory)
poll([{fd=5, events=POLLIN}, {fd=11, events=POLLIN}], 2, 3995) = 0 (Timeout)
inotify_add_watch(11, "", IN_MODIFY|IN_ATTRIB|IN_CLOSE_WRITE|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE|IN_DELETE_SELF|IN_MOVE_SELF|IN_UNMOUNT|IN_ONLYDIR) = -1 ENOENT (No such file or directory)
poll([{fd=5, events=POLLIN}, {fd=11, events=POLLIN}], 2, 3996) = 0 (Timeout)
inotify_add_watch(11, "", IN_MODIFY|IN_ATTRIB|IN_CLOSE_WRITE|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE|IN_DELETE_SELF|IN_MOVE_SELF|IN_UNMOUNT|IN_ONLYDIR) = -1 ENOENT (No such file or directory)
poll([{fd=5, events=POLLIN}, {fd=11, events=POLLIN}], 2, 3995) = 0 (Timeout)
inotify_add_watch(11, "", IN_MODIFY|IN_ATTRIB|IN_CLOSE_WRITE|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE|IN_DELETE_SELF|IN_MOVE_SELF|IN_UNMOUNT|IN_ONLYDIR) = -1 ENOENT (No such file or directory)
poll([{fd=5, events=POLLIN}, {fd=11, events=POLLIN}], 2, 3996) = 0 (Timeout)
inotify_add_watch(11, "", IN_MODIFY|IN_ATTRIB|IN_CLOSE_WRITE|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE|IN_DELETE_SELF|IN_MOVE_SELF|IN_UNMOUNT|IN_ONLYDIR) = -1 ENOENT (No such file or directory)
poll([{fd=5, events=POLLIN}, {fd=11, events=POLLIN}], 2, 3996) = 0 (Timeout)
inotify_add_watch(11, "", IN_MODIFY|IN_ATTRIB|IN_CLOSE_WRITE|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE|IN_DELETE_SELF|IN_MOVE_SELF|IN_UNMOUNT|IN_ONLYDIR) = -1 ENOENT (No such file or directory)
poll([{fd=5, events=POLLIN}, {fd=11, events=POLLIN}], 2, 3995) = 0 (Timeout)
inotify_add_watch(11, "", IN_MODIFY|IN_ATTRIB|IN_CLOSE_WRITE|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE|IN_DELETE_SELF|IN_MOVE_SELF|IN_UNMOUNT|IN_ONLYDIR) = -1 ENOENT (No such file or directory)
poll([{fd=5, events=POLLIN}, {fd=11, events=POLLIN}], 2, 3996) = 0 (Timeout)
inotify_add_watch(11, "", IN_MODIFY|IN_ATTRIB|IN_CLOSE_WRITE|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE|IN_DELETE_SELF|IN_MOVE_SELF|IN_UNMOUNT|IN_ONLYDIR) = -1 ENOENT (No such file or directory)
poll([{fd=5, events=POLLIN}, {fd=11, events=POLLIN}], 2, 3995) = 0 (Timeout)
inotify_add_watch(11, "", IN_MODIFY|IN_ATTRIB|IN_CLOSE_WRITE|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE|IN_DELETE_SELF|IN_MOVE_SELF|IN_UNMOUNT|IN_ONLYDIR) = -1 ENOENT (No such file or directory)
poll([{fd=5, events=POLLIN}, {fd=11, events=POLLIN}], 2, 3996^Cstrace: Process 10689 detached
 <detached ...>
````

# Does not hang with Kernel 4.9.80
* Hangs with Kernel 4.14.17
* Hangs with Kernel 4.14.13
* Hangs with Kernel 4.14.3
# Does not hang with Kernel 4.13.12

How to reproduce:

Mount Samba or Windows share
Create or empty local junk folder
Do not use command line copy tools. You must use a GUI file manager.
Drag n drop copy a large folder with lots of different file types from the share to the local junk folder.

**Comment by alex-teixeira** [comment]
I'm running Linux Mint 19 up to date and facing the same problem. I have a folder mounted using cifs and every time I copy a text file, or a folder with a text file in it Nemo freezes. It freezes even with a 15kb text file. All other files seems ok no matter the size.

**Comment by mp-smith** [comment]
An update re: my experience (original post 2018-01-30). My problem is resolved.

My best guess is that some package in a major F27 update(152 packages) I did on 2018-07-13 fixed the hangs when writing to my CentOS7 Samba server from F27 w/Nemo. I'm a happy camper again. 

I still have no clue what the real root cause was. However, the following potential culprits were included in the update:
   + libsmbclient-2:4.7.7-0.fc27.x86_64
   + samba-client-2:4.7.7-0.fc27.x86_64
   + samba-client-libs-2:4.7.7-0.fc27.x86_64
   + samba-common-2:4.7.7-0.fc27.noarch
   + samba-common-libs-2:4.7.7-0.fc27.x86_64
   + samba-dc-libs-2:4.7.7-0.fc27.x86_64
   + samba-libs-2:4.7.7-0.fc27.x86_64

**Comment by CottonEaster** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This and other problems have made me move to using an alternative file manager, namely, pcmanfm. Pcmanfm doesn't look as good as Nemo, and lacks some of Nemo's functionality. (The 'qt' version of pcmanfm looks better, but configuring those looks is highly involved.) But at least pcmanfm does not abort copies and - when I take my laptop out of my house - stall heavily when network shares are unavailable.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;It seems to me that these problems with Nemo - in other respects is an _excellent_ file manager - are _very serious_ and are not getting the attention they warrant. A file manager needs to allow a laptop to leave the house and, you know, to copy files. Some of the problems may originate in cifs or in systemD; but if pcmanfm can work around such problems, so can Nemo. Let's make Mint Cinnamon 'ready for the desktop'.

**Comment by begleysm** [comment]
Totally agree @CottonEaster.

I did a bit more experimenting.

Nemo hangs on seemingly random files.  Just 1 or 2 in a folder of 40+ images.

Comparing a file that works to one that doesn't (both on the client and server) show identical owners, permissions, and ACLs.

I was able to successfully copy a file that hangs in Nemo with scp, cp, and Windows 10 machine.

Furthermore, deleting the offending file off of the server and then putting a "new" file in its place (same name) causes a failure as well.

**Comment by CottonEaster** [comment]
@developers: do you manage to reproduce this (sort of) bug?

**Comment by begleysm** [comment]
Hmm... Got the same result with PCmanFM...

Again though, not with cp, scp, or a WIndows 10 machine...

**Comment by CottonEaster** [comment]
begleysm: what version of Mint are you using? Mint 19? I have just tried and failed to reproduce the file copying problem, both with pcmanfm and with Nemo. (A problem with samba is that there are so many variables - so many things that could cause problems.)

**Comment by begleysm** [comment]
I'm running Linux Mint 18.2.

Perhaps I'll try to upgrade to 19.  Sometimes those upgrades are scary ;)

**Comment by jretropie** [comment]
Linux Mint 19 still have this problem.  Only Nemo has this problem.

cp, mv using command line does not have this problem.

**Comment by begleysm** [comment]
I don't think the filetype has much of an impact.  I've had it happen with image files as well.  But, as with you guys, I've had it happen on nemo and pacmanfm, but not on cp or scp.

**Comment by CottonEaster** [comment]
I think it needs stressing that this is a fairly big problem. For, not only

1) does a copy hang indefinitely

but also (at least on my system)

2) I get a hung app (Nemo, or PcManFM) that will not close easily (it has to be terminated)

and

3) I get an indicator I can't get rid of (except by restarting Cinnamon) in my panel.

**Comment by jretropie** [comment]
I have to use the command line "**xkill**" to kill the copying process. 

I think Nemo has this problem for fairly long time and NEVER GET FIX. See here the post from 2012:
https://forums.linuxmint.com/viewtopic.php?t=117647

**Comment by bstie** [comment]
I had the same Problem with Linux Mint 19 and nemo when copying files from/to network drives. Then I installed nautilus and now it works fine :slightly_smiling_face:

**Comment by obifur** [comment]
I tested the following on Mint 19:
- Ubuntu 4.15.0-34.37-generic 4.15.18
- cinnamon: 3.8.9+tara
- nemo: 3.8.6+tara
- samba-common: 2:4.7.6+dfsg~ubuntu-0ubuntu2.2
- cifs-utils: 2:6.8-1

a)
1. mount samba share (Qnap TS251) via autofs/cifs
2. create txt-file, no matter wich name or with or without extension, but NOT emty
3. copy from samba share to local HDD/SSD
Result: Nemo AND Nautilus hang at the END of the copying process (after killing filemanager the file is existing completely)

b)
copy from local HDD/SSD to samba share 
Result: no problem

c)
1. access samba share (Qnap TS251) via smb://
2. copy from samba share to local HDD/SSD
Result: no problem

So for me every txt-file hangs as long it is not emty.. tested with Nemo and Nautilus, cp via terminal works without problems.

**Comment by dabeastro** [comment]
This issue has been documented pretty welll with no resolution in sight. I test with all versions of smb (1.0, 2.1, 3.0) and got a hang on just about any file that is human readable (ini, htm, txt, etc). I test out at least 4 file managers including pcmanfm, nautilus, and thunar. This is definitely a cifs/smb package issue.

https://bugzilla.samba.org/show_bug.cgi?id=13252

**Comment by CottonEaster** [comment]
'This is definitely a cifs/smb package issue' - and so, you mean, not a problem that _Mint_ needs to fix?

Either way, I wish to goodness that the problem would be solved. Samba being really slow (#424) and, especially (the issue of this the present thread) just hanging, is, surely, a basic brokenness that embarrasses Linux and seriously inconveniences users of Mint and users of any other affected distribution.

@mtwebster : anything you can do, please?

**Comment by obifur** [comment]
I never faced this issue with Kubuntu (bionic). I just switched to Mint 19 around four weeks ago.. how does that fit together? Maybe I should reinstall it to confirm.

**Comment by obifur** [comment]
Ok, I was really annoyed about this, so I switched back to Kubuntu - This bug does not exist here!

- Kubuntu 18.04 LTS
- Kernel 4.15.0-38-generic on x86_64
- Dolphin Version 17.12.3
- samba-common Version: 2:4.7.6+dfsg~ubuntu-0ubuntu2.2
- cifs-utils Version: 2:6.8-1

**Comment by blackmyre** [comment]
I'm also suffering badly with this. Mint versions 18.1 and 18.3 with 4.13.x kernels work fine but it's broken with 4.15 kernels (on 18.3 and 19). Symptoms as others have described: copying text files *from* an fstab-mounted SMB share with a GUI file manager (Nemo, Nautilus) hangs at completion of first file with the progress dialog indicating it's still trying. Copying *to* the share wirks fine. Copying in a terminal using cp command works fine, it's just the GUI.

Is this the best place to be reporting this or should it be filed as a bug elsewhere? Is there anything else I can do to characterise the problem?

**Comment by CottonEaster** [comment]
@severach @severach 

It does seem significant that this problems occurs only with certain kernels. It seems to me that we should indeed ask whether this is a problem that needs reporting upstream. We need to get a Mint developer to advise on this, I think. Earlier/above I tried paging Michael Webster but there has been no response on this page.

**Comment by krisspringer** [comment]
I've been experiencing the same issue for a few months now.  If I copy/paste 1 file at a time all is well.  But if I try to copy more than 1 it hangs exactly like everyone is describing.  It occurs on different machines with different flavors and kernels, and in both nautilus and nemo.  I currently connect to my NAS via cifs mounts in my fstab file, but I'm thinking about looking at a different protocol because something is obviously broken.  Same problem on all these,
Ubuntu 18.04, kernel 4.15.0-39
Mint 18.3, kernel 4.13.0-45
Mint 18.3, kernel 4.15.0-39

I haven't found a functional solution yet.  I'm testing newer kernel and will post my results.

**Comment by two-dogs** [comment]
> I never faced this issue with Kubuntu (bionic). I just switched to Mint 19 around four weeks ago.. how does that fit together? Maybe I should reinstall it to confirm.

@obifur , you said ^^, the only thing kde does diff is the use of kio-slaves instead of gvfs, kio works from what you said, everything else was common to both desktops.

**Comment by luc77** [comment]
Same situation here on mint 19 (with permanent cifs mount on the fstab) other machines I have on Mint 18.x have no problems.

Only cifs mounts are affected, gvfs user mounts always work and the problem seems to happen regardless of the file manager used (but I have only tested a few). Command line tools always work.
I experimented with different kernel versions and here is what I found:

All kernels before 4.12.x work well. (on the tests I've done methodically I only used SMB 3, but some random checks on SMB 2 and 1 shown always the same)

All mainline kernels from 4.12.0 to 4.19.2 were tested and in all of them, without exception, this GUI FM bug is present. Some change introduced from kernel 4.11 to 4.12 is apparently causing this problem.

I'm currently using Mint 19 with kernels 4.11.0 and 4.11.12 and all works fine.

**Comment by jake7301** [comment]
I'm having the same issue on ArchLinux kernel 4.19.2, however, I found a temporary workaround.  Add vers=2.0 to your mount command.  I tried SMB 2.1 and 3.0 and they both had the problem.  However, going down to version 2.0 seems to work.  Of course, this seems to be a temporary workaround because we don't know when Microsoft will stop supporting SMB version 2.0.  However, my Windows machines are running Windows 10 and it still works for me.

Now, I don't want to take credit for this idea.  I was following the bugzilla report below (it seemed to be the same problem).
https://bugzilla.kernel.org/show_bug.cgi?id=198349
cs_gon reported the success with version 2.0.  I'm just sharing the idea here because it worked for me (at least for now).

**Comment by mneiger** [comment]
Very similar here. I reverted to vers=2.0 for the time being but it's not satisfactory.

**Comment by luc77** [comment]
Here adding vers=2.0 to the mount did not solve it for a WesternDigital NAS (this NAS also supports the option to limit the max SMB to 2.0 or even 1.0. I have tried all sort of combinations but no success). As for me kernel 4.11 seems to be working great I'm ok with this solution. I trust the kernel guys will take a look into this and the bug will vanish in kernels to come.

**Comment by jretropie** [comment]
vers=2.0 does not work for me.

**Comment by mneiger** [comment]
here is a matrix of several tests using a QNAP TS-251 as file server, Mint 18.3 as client
I'm currently considering switching to kernel 4.13 and user vers=3.0

Kernel/vers | 2.1 | 3.0 | 3.11
-- | -- | -- | --
4.13.0-45 | Y | Y | N
4.15.0-39 | N | N |  
4.17.0.19 |   | N |  
4.19.3 | N | N |

**Comment by CottonEaster** [comment]
@mneiger : so 'Y' means works?

**Comment by mneiger** [comment]
here is a more complete matrix using an OMV server
Client is mint 19

Y : seems to work (I don't have enough working time to affirm it)
N : does not work.

Kernel/vers | 2.0 | 2.1 | 3.0 | 3.1.1
-- | -- | -- | -- | --
4.13.16 |   | Y | Y |  
4.14.83 | Y | N | N | Fails mount
4.15.0-39.42 | Y | N | N | Fails mount
4.17.19 | Y |   | N | N
4.19.4 |   | N | N | N

I'll stick to 4.15 and vers=2.0 (I need 4.15 for the client hardware) but performances seem better with vers=3.0

**Comment by elfalem** [comment]
I'm also experiencing this issue. In my case copying files from one directory in an fstab mounted CIFS share to another directory in the same share hangs. Issue is present in nemo and pcmanfm. Additionally,  writing to a sqlite db located on the share from a .net core application stalls for sometime and throws a `database is locked` exception. I've reverted back to the 4.10 kernel as it's the only version working for me.

Mint 19
samba-common 2:4.7.6+dfsg~ubuntu-0ubuntu2.5
cifs-utils 2:6.8-1

kernels tested
4.10.0-35 working
4.15.0-43 not working
4.15.0-20 not working
4.18.0-13 not working

**Comment by adanielvv** [comment]
I am experiencing this problem with files smaller than aprox. 5 KiB, whether .txt or otherwise.
(Server: Ubuntu 18.04, Desktop: Ubuntu 18.04, mostly default setup (vers=3.0). Workaround: Server Ubuntu 16.04 or: vers=2.0)

**Comment by CottonEaster** [comment]
@nitftw

So only certain kernels work (with Mint 19.1)? This is silly. Indeed I found just now that Nemo hung - horribly; I had to log out - when copying a folder - containing text and other files - from a _Flash_ drive. This is just too much. Also, I need newer kenels for my (new) hardware.

**Comment by jake7301** [comment]
I researched this issue some more and it appears Reiny in the bug report below has done some great work on this issue.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=886049

Since he appears to understand this issue better than anyone else (at least as far as I know), then he would probably be the best one to help resolve the issue.  However, if I understand the work Reiny has done (please keep in mind I'm not a developer), it looks like there are a few options that would fix this.

1) The splice() function could be fixed in the Kernel.  Below is the bug report for this, unfortunately, it doesn't seem to be getting a lot of attention.
https://bugzilla.kernel.org/show_bug.cgi?id=198349

2) According to Reiny's work it appears the library libglib2.0-0 could be changed and call the splice() function differently.  It looks like a test program was created that called splice() differently and Reiny reported that it fixed the issue (here is the link to the test program https://gist.github.com/karthick18/1234187).  I'm not 100% sure who maintains the library libglib2.0-0, but if they could look at the source code from this test program and modify libglib2.0-0 so it called splice () the same way it seems like that will solve the issue.  More research needs to happen to find who is maintaining libglib2.0-0, but it might be https://gitlab.gnome.org/GNOME/glib.

**Comment by CottonEaster** [comment]
This Reiny person appears to have put in a lot of impressive work - seemingly, so far, for nothing. I just do not understand. How are the enterprise versions of Linux managing, given this bug? And, given the Mint users affected, are the Mint developers doing anything to help resolve this serious problem?

**Comment by severach** [comment]
Kernel 3.10 and no GUI, no problems.

**Comment by jake7301** [comment]
I might have found a different workaround.  In my limited testing, if I used gvfs instead of mounting the server's share I didn't have lockups.  I use Archlinux not Mint so I can't say whether gvfs, and gvfs-smb are installed by default on Mint.  However, if those packages are available, instead of mounting the share, access the share by typing {smb://server_name/share_name} into the path.

I'm running Archlinux, kernel version 4.20.3, gvfs version 1.38.1, and nemo version 4.0.6-2

So far I haven't had lockups when I access the server this way.

**Comment by CottonEaster** [comment]
@jake7301 

That sounds hopeful. I have `gvfs` but not `gvfs-smb` and I can't seem to find the latter in the repositories. Assuming I could get that setup installed: can one make shortcuts - within folders, and in panes in file managers - to paths of the type you mention?

I am hoping also that my having switched to SMB v. 2 for my mounts might help to0.

**Comment by jake7301** [comment]
@CottonEaster 

I don't know Mint, so maybe all you need is gvfs.  With Archlinux I had to install both gvfs and gvfs-smb.

Regarding shortcuts, I just created a Bookmark in Nemo to a few of my network shares.  That way I don't have to manually retype the path.  

So far it's working well, but I have only done limited testing...

**Comment by CottonEaster** [comment]
@jake7301 

Thanks. Sorry to bang on, but: for this method one doesn't need any fstab entry or systemd mount point?

**Comment by jake7301** [comment]
@CottonEaster 

No, I didn't do anything with fstab or systemd mount point.  However, I don't have my shares mounting automatically so if you do, that could be a difference.  

Once I installed the gvfs packages I simply opened Nemo and typed smb://server_name/share_name into the path (I didn't do any configuration with gvfs at all).  I was prompted for the username and password (the username and password of my server).  From there I was able to copy files from my server.  It was pretty slick and easy.

Also, Nemo does have a Connect to Server option (under File).  I tried it and it worked the same way.  So, if you prefer that option instead of typing the path it seemed to work.

Now, I still haven't had time to do complete testing, but so far I haven't had any problems.

**Comment by CottonEaster** [comment]
@jake7301 

Thanks; I've set it up, and it is working fine so far (except KeePass can't manage to access the network locations; I'll try to fix that).

**Comment by jretropie** [comment]
How do you make sure to use gvfs instead of cifs when you just type the path to access?

**smb://server_name/share_name**

**Comment by jake7301** [comment]
@CottonEaster 

as far as KeePass...  For me, once I connect to the server via Nemo, I can access the server through gvfs using it's mount point.  For me the mount point is /run/user/1000/gvfs/smb-share:server=192.168.1.1,share=jake

I'm sure your mount path will be a little different but it should be very similar.

**Comment by CottonEaster** [comment]
Yes, I tried 'smb://server_name/share_name', thank you. Still, KeePass is something of a disaster on Linux - theming wise, and speed wise, so I'm trying KeePassXC, but it doesn't have sync, and: (1) getting any sort of cloud storage provider working via GUI on Linux (Mint anyway) is a nightmare; (2) I'd rather not have my passwords in the cloud anyway. But I'll see what I can do.

But, ah, you've come up with some wizardry for KeePass proper. Well done - and thank you! I'll see - now that I have a native interface, I don't want to give it up . .

**Comment by jake7301** [comment]
@jretropie 

> How do you make sure to use gvfs instead of cifs when you just type the path to access?
> 
> **smb://server_name/share_name**

I mounted my server using cifs and using gvfs at the same time to test this.  For me, my cifs mounts appear in Nemo's Sidebar under Devices.  The gvfs mounts appear in Nemo's Sidebar under Network.

**Comment by jretropie** [comment]
when I used the command "gvfs-mount smb://server_name/share_name"

it said **This tool has been deprecated, use 'gio mount' instead.
See 'gio help mount' for more info.**

**Comment by CottonEaster** [comment]
@jake7301 
Thank you very much for your help. The full path to my KB database, complete with share gubbins, turns out to be

/run/user/1000/gvfs/smb-share/KeePass.kdbx:server=<ip>,share=keepasssync

and indeed I can `cd` to `/run/user/1000/gvfs/smb-share/`. Yet, when I use that in KeePass it gives me an error message - in dark grey, on a black background; I cannot read it.

**Comment by jake7301** [comment]
> @jake7301
> Thank you very much for your help. The full path to my KB database, complete with share gubbins, turns out to be
> 
> /run/user/1000/gvfs/smb-share/KeePass.kdbx:server=,share=keepasssync
> 
> and indeed I can `cd` to `/run/user/1000/gvfs/smb-share/`. Yet, when I use that in KeePass it gives me an error message - in dark grey, on a black background; I cannot read it.

Sorry, I'm not sure what the problem is...  I have KeePass myself and I can open my database through the gvfs mount point.  In KeePass I click the Open Database File icon.  Then at the Open Database File box, I select My Computer on the left side.  Then I double click on HDD (sda2 in my case), then double click on run, then double click on user, then double click on 1000, then double click on gvfs, then double click on the smb-share...............  folder.  When going through that process at what point does it give you the error?

**Comment by CottonEaster** [comment]
@jake7301 

I did not try that cumbersome method of opening a database. Rather, I am trying to use KeePass 'triggers' to sync my database (which is on my local computer) with another computer. Just now I tried a somewhat different path to do that and KeePass put up a nice window asking for credentials and . . would not let me access the file. Screenshot:

![image](https://user-images.githubusercontent.com/9998846/51774005-a5f04800-20e8-11e9-9bbb-c1f7be2bee35.png)

**Comment by jake7301** [comment]
> @jake7301
> 
> I did not try that cumbersome method of opening a database. Rather, I am trying to use KeePass 'triggers' to sync my database (which is on my local computer) with another computer. Just now I tried a somewhat different path to do that and KeePass put up a nice window asking for credentials and . . would not let me access the file. Screenshot:
> 
> ![image](https://user-images.githubusercontent.com/9998846/51774005-a5f04800-20e8-11e9-9bbb-c1f7be2bee35.png)

Sorry, I don't know enough about KeePass' Open URL interface to know what it's doing.  However, it appears it doesn't have hooks to gvfs.  Sorry, I'm not much help here...

I'm just storing my database file on my server and then I can use it via the smb share.  Opening it through the GUI was cumbersome the first time, but after that it remembers the location so it's only cumbersome the first time.

One other thing...  I have had my server mounted via cifs and gvfs at the same time without any problems.  I don't know if the cifs bug that is affecting Nemo would affect KeePass, but if not then you could use the cifs mount for KeePass but use gvfs for Nemo.  It's just a thought...

Sorry, I'm not much more help.

**Comment by CottonEaster** [comment]
>  I don't know if the cifs bug that is affecting Nemo would affect KeePass, but if not then you could use the cifs mount for KeePass but use gvfs for Nemo. It's just a thought..

Yes, I suppose so - and I had no thought of that. Thank you. I will try it if I do not get on with KeePassxc combined with DropBox. I managed to get DropBox to run on Mint, for the first time in years, with minimal (but some) breakage. However, KeePassxc, despite being nice in some ways, appears to have some desperate UI limitations, so we will see. Thank you again for all your help. I do appreciate it.

**Comment by rwpreece** [comment]
As suggested above by @mneiger I tried setting my vers=2.0 in my fstab mounts and it seems to have solved the copy from cifs mount to local machine hang.

I'm running Linux Mint 19.1 Cinnamon (v4.0.9) with kernel 4.15.0-43-generic.

Here's my mount from fstab:
//server.company.com/intranet /media/intranet cifs uid=rwpreece,credentials=/home/rwpreece/.smbcredentials,noauto,users,vers=2.0 0 0

The following bug report, which is nearly complete, may be related to this problem as I get the same windows network directory empty issue until I set vers=1.0.  Samba just needs to fix something on their side:
https://bugs.launchpad.net/ubuntu/+source/gvfs/+bug/1778322
There is a fix in gvfs for this but it depends on the fix from Samba (see very end of bug comments).

I must say that I cringe everytime i get an update for any Samba libraries because they have broken things a at least 3 times in the last 7 or 8 years.  Someone needs to donate some some equipment to Samba for testing purposes, specifically regression testing.

Solution to this break may also be replacing your server.company.com with it's IP address.  From my reading it appears the break is that Samba's SMB3 (vers=3.0) does not resolve server names to IP addresses.

Hope this info helps.

Roger

**Comment by blackmyre** [comment]
**@rwpreece** I'm also using Mint 19.1 "Tessa" with the same kernel and version of Cinnamon, but it still fails for me. Binary files (e.g. .jpg) work fine but copying/moving files containing plain text from a cifs-mounted share causes problems. When copying a mixture of file types it succeeds until reaching the first text file. It successfully copies that file, but pops up the progress window and goes no further. Nemo remains responsive and will happily copy files (including text files) _locally_ but any further attempts to copying anything from (or to) the cifs share are blocked.

The file extension doesn't seem to matter, it also fails with .xml/.md and so on. Copying **to** cifs seems to work just fine for all files.

My fstab mount line didn't include the 'noauto,users' options and omitted the trailing zeros (which I believe are default values) but is otherwise of the same form as yours. I get the same results when I change mine to exactly match your form.

**Comment by rwpreece** [comment]
@blackmyre Try **one or more** of the following:

1) Change your server name to it's IP address (from terminal window enter: ping yourserver.company.com to get the IP address) in your /etc/fstab file.  Save the file.  You may need to unmount and remount your drives.  Worst case you may need to logout and login or reboot.

2) Change the vers=2.0 to vers=1.0 in your cifs mounts.  Please be aware that version 1.0 has security issues so 2.0, 2.1 or 3.0 are preferred.  Save your fstab file.  You may need to unmount and remount your drives.  Worst case you may need to logout and login or reboot.

Here's the format I ended up with after the previous fix stopped working for me too:
//999.999.999.999/intranet /media/intranet cifs uid=rwpreece,credentials=/home/rwpreece/.smbcredentials,vers=3.0 

One of the problems with this release of Samba is that the vers=3.0 protocol does not resolve DNS names to IP addresses so changing your server name to it's IP address may let you use the faster vers=3.0 protocol.

Also, you can experiment with different versions to see which works best on your networked file shares.  They may be using an older protocol.  So try vers=1.0 or vers=2.0 or vers=2.1 or vers=3.0 to see what works best.  Also, you can remove the vers= setting all together and let your client negotiate the protocol with the samba servers/networked file shares.

**Comment by sirken** [comment]
Confirmed on Mint 19 MATE

- Samba server is Mint 19
- clients are all Mint 19.1 with Kernel 4.15
- clients mount samba shares via /etc/fstab
- GUI file managers such as Caja and Pcmanfm will copy TO the samba shares but hang when copying FROM them
- Command line copying works without issues

Adding vers=2.0 to the fstab entries worked
Adding vers=3.0 did not work. Did not try other versions

**Comment by Denkevich** [comment]
Adding vers=2.0 to the fstab entries worked - Not a solution! LibreOffice is not working correctly with SMB vers=2.0. I have 22 computers in my office with this problem. Is there no solution?

**Comment by adanielvv** [comment]
@Denkevich Adding vers=1.0 worked for me.

**Comment by Frankstar** [comment]
"worked" is the right term. sure it works, but its still just a workaround.
you have a lot of drawbacks with vers=1.0

anyway this is not a NEMO or Mint problem.
i have the same problem in Fedora 29 with Nautilus / other Programs and SMB.

**Comment by nixftw** [comment]
Looks like it is a kernel issue. So far the only the solution is, use a different kernel.

I have 4 laptops running Mint 19.1 with kernel 4.13.16-041316-generic, and

no problems.

**Comment by Denkevich** [comment]
Where to get kernel 4.13.16-041316-generic for Linux Mint 19.1?
Hereж https://kernel.ubuntu.com/~kernel-ppa/mainline/v4.13.16?

**Comment by nixftw** [comment]
I used ukuu - https://www.omgubuntu.co.uk/2017/02/ukuu-easy-way-to-install-mainline-kernel-ubuntu, for those who want to downgrade.

**Comment by blackmyre** [comment]
@rwpreece I am already using IP address rather than hostname in my fstab entry, that doesn't prevent the problem. I can't change the version because the machine providing the share is a NAS drive that only supports vers=2.0. 

Thanks for the suggestions though and apologies for the late response, I only just spotted your reply of 30 Jan.

**Comment by krisspringer** [comment]
This is an Ubuntu kernel problem that has existed for a while.  The title of this thread talks about txt files, but it's any file type.  I experience the hanging issues in the GUI, but also when using SMB or NFS via command line tools.  Rsync hangs randomly requiring a reboot to escape the problem.  I thought it might be an rsync issue so I tried other command line tools and experienced the same problems.  I did many tests with different tools using both SMB and NFS with old kernels and new kernels, all have the same trouble.  There's something wrong with the Ubuntu kernel.  It's disheartening that there's a core problem with the kernel that isn't getting fixed.  I'm going to test Kali and see what happens since they compile their own kernel from a different Debian branch.

**Comment by blackmyre** [comment]
@krisspringer Your experience does not correspond with mine. For me it is **not** any file type, it's just files containing plain text (regardless of extension), and **only** when using a GUI file manager (Nemo in my case). Binary files (jpg, pdf, executables) copy just fine using Nemo, and the cp command in a terminal window works flawlessly with all ffiles, including the text files that cause problems for Nemo.

**Comment by Frankstar** [comment]
well i dont even use crapbuntu and have the same issue - so i think its just the smb package.

**Comment by nixftw** [comment]
Frankstar, If your read the above threads, you will see that it is not ubuntu specific, people running Fedora have the same issue. It is not the smb package, it is a kernal issue.

**Comment by jake7301** [comment]
The issue has been reported to the kernel developers, and a bugzilla issue was opened and it was even assigned an importance of "P1 high".  The link is below.

https://bugzilla.kernel.org/show_bug.cgi?id=198349

Unfortunately, this bugzilla issues was opened on 1-4-2018, but it doesn't appear the kernel developers have done much with it.  There is someone named cs_gon that is trying to work on it, but cs_gon isn't getting much help from the main kernel developers.  To truly solve this problem I think we need to find a way of getting the kernel developers attention, and getting cs_gon some help.

**Comment by mneiger** [comment]
Hi all,

I don't know what did recently change but the new kernel serie 4.19.32 appears to be working fine.
There's been some activity at https://bugzilla.kernel.org/show_bug.cgi?id=198349 which is likely the same bug.

Here is my updated table. Feedback is welcome.

Kernel/vers | 2.0 | 2.1 | 3.0 | 3.1.1
-- | -- | -- | -- | --
4.13.16 |   | Y | Y |  
4.14.83 | Y | N | N | Fails mount
4.15.0-39.42 | Y | N | N | Fails mount
4.17.19 | Y |   | N | N
4.19.4 |   | N | N | N
4.19.32 | Y | Y | Y | Y
  |   |   |   |

**Comment by jake7301** [comment]
mneiger, thanks for noticing the kernel team implemented a fix.  It is now working well for me as well...  I'm using kernel 5.0.5.  It works when I set the version to either 3.0 or 3.11 or when I don't set the version and just use the default.  However, one really important piece is to make sure oplocks is turned on (without this option turned on it failed).  When I upgraded to kernel 5.0.5 I had to manually turn this on.  You can check this setting using the command below.

cat /sys/module/cifs/parameters/enable_oplocks

If it's set to Y everything worked great for me.

If it's set to N you can turn it on with the command below.

echo Y > /sys/module/cifs/parameters/enable_oplocks

I decided to remove the vers option from my mount command, and let it just use the default.  So far its working great for me...

**Comment by dannn-o** [comment]
I had been encountering the same symptoms described by the original poster using Linux Mint 19, and had been using Dolphin in cases where I needed to transfer files that would hang up Nemo.  But, I have gotten accustomed to (and prefer) Nemo over the years, and although I was a bit wary to try upgrading the kernel as suggested by @mneiger above, I calmed my fears by reading various posts online with instructions for the process, and decided to give it a try.

I'm glad I did, because installing 4.19.32 (generic) appears to have resolved the problem for me as well.  I've only been running with the new kernel for a part of this evening, but I did some testing with applications that normally regress (according to what I saw in the posts I read), like Virtualbox, and so far things seem to be running smoothly.  In fact, my transfer rates on the wireless adapter (802.11 ac) appear to have gotten about a 40% boost in speed with the new kernel (compared to v 4.18.0, which I had been on).  Also, it's a bit anecdotal but the progress indicator that Nemo shows during larger file transfers now appears to be more accurate and consistent.

BTW - I had first tried forcing my CIFS mounts to use SMB v2.0 in FSTAB, as some had suggested.  And, it did avoid the issue of Nemo hanging during transfers.  But, it also took quite a bit longer for transfers to complete from start-to-finish, with an appreciable delay before the progress indicator would even start to update.

**Comment by elfalem** [comment]
I have updated to kernel 5.0.0-23 on Mint 19 and the issue seems to have been resolved. The last kernel that worked for me was 4.10.0-35

**Comment by luc77** [comment]
I have tested several 5.x kernels on mint 19 and it did not solve the problem over here. I got stuck in the 4.11 kernel (the last one that works for me).

Three different PC hardware are used here, asus, hp and dell, mint 19.0 and 19.2. The only common thing is the WesternDigital EX4100 NAS server. Since others have the 5.x kernels working I would suspect something specific to my NAS that however woks well on gvfs mounrs and in other OS's in general. Only linux cifs mounts with certain kernels have this issue.

This leads me to think that there is something related with kernel not implementing tolerantly-enough the SMB protocol that results in mounts to specific servers to exhibit the problem while other users with different servers don't have issues. Also explains some kernels will work for some users while the same kernel does not work well for other users.
Additionally, to add this the conjecture, over here the 5.x kernels exhibit yet another strange behaviour regarding cifs mounts. Mounting cifs at fstab no longer works, while mounting cifs at command line works perfect, the _nodev option does not help it will not work the same.

I suspect that this subject may have not been specifically addressed in the recent kernel revisions, I rather think the variability it has with symptoms appear and disappear from version to version and exclusively for cifs mounts may not gain the status  of a kernel issue that needs to be addressed.

I wish there is a way to really alert kernel developers to this.

lc,

**Comment by SoftwareSchlosser** [comment]
Same problem here with Linux Mint 20 Kernel 5.4.0.
In fact the file gets copied over but nemo hangs at 0%. When moving files, the source file aren't deleted.

**Comment by blackmyre** [comment]
It seemed to be working again for me in Mint 19.2 but broken again since. My current thinking is that it's a consequence of an issue with the glib library and Samba. My understanding is that the glib routines rely on being able to rename temporary files while they're still open, but that's not supported by Samba shares. A result is that writing a change to an existing file on a Samba share will fail when carried out from a GUI application that uses the glibc library (saving a change with a text editor such as xed, copying over an existing file with a file manager such as Nemo). The equivalent actions from the command line succeed because they don't use glibc. See https://forums.cix.co.uk/secure/thread.aspx?forum=linux&topic=17general&msg=2641 for details.

**Comment by Tobias-Doerner** [comment]
Same issue occuring on my system if I'm trying to copy or move a text file from a share destination to a share destination.

My client system is a Linux Mint 20.0 Cinnamon, Kernel 5.13.0-23-generic, nemo 5.0.5
and server system is a Synology DS918+, DSM 7.0.1-42218, SMB Version 3

I was able to fix the error in my environment by changing my server configuration by selecting the **"Enable Opportunistic Locking"** option.

**Comment by blackmyre** [comment]
I noticed a while ago that it was working for me too. I'm now using a different client machine and running Mint 20.3 Cinnamon (Kernel 5.13.0-22) but I'm not sure when it changed. Some scrappy notes indicate that it may have been related to the mount having been systemd-controlled and that reverting to old-school fstab mounts fixed it. No idea if that makes sense (I kind of thought systemd did it under the covers anyway these days) but it's working so I'm leaving it alone!

**Comment by AtomicRobotMan0101** [comment]
Had a **big deep dive** into this and it appears to be a Kernel bug, not one with Nemo.

Let me elaborate (Ive added lots of details for n00bs/novices who may be experiencing this unholy scenario)

Using Mint Cinnamon 21.1 with Kernel 5.15.0-60, with a CIFS mounted disk.  The disk is /sda1 on the main router (USB connected, to a TPLink Archer C1200, latest firmware). The mount options are ancient and decrepit... SMB 1.0.  Disk is formatted to NTFS (this doesn't matter)

Unmounted, one can use NEMO to map the server via the File --> Connect To Server and use it merrily (no issues).

However, if the drive is mounted via fstab (see `sudo nano /etc/fstab`)  Nemo will attempt to transfer some files, then suffer a seizure and hang.  The hangs are random and usually somewhere towards the ends of the files transfer.  It is entirely reproducible.

This is the usual style of fstab mount: `//192.168.1.1/sda1 /media/NAS cifs vers=1.0,username=admin,password=admin 0 0`

Doing a manual mount has the same result... e.g. `sudo mount -t cifs -o soft,vers=1.0,username=admin,password=admin //192.168.1.1/sda1 /mnt/NAS`

The `soft` option was used as an attempt to time out the hang. It doesn't work.

OK, is there a solution?  Yes, roll back the Kernel to one that works.

Let me explain more.  This option is not without pain.

I traced the bug down through the layers and it appears a Kernel Dev has made a regression to a critical piece of code that serves the Ver 1.0 SAMBA time-out and slots functions. When NEMO is doing a transfer, is is relying on underlying code to return a value. The buffer that is handling this is full and doesn't release, hence the BLOODY HORRIBLE effect of a pestilential copy attempt, the inability to kill the pop-up, a stuck transfer queue and the piling up of further jobs.

The only solution to log out of ones session. I have not found a way to kill/flush the underlying buffer other than this.

More info is here: https://bugzilla.kernel.org/buglist.cgi?bug_status=__open__&component=CIFS&list_id=1123993&order=changeddate%20DESC%2Cbug_status%2Cpriority%2Cassigned_to%2Cbug_id&product=File%20System&query_format=advanced

There is little we can do as users to patch this, at this time. we can see from the discussions that the bug is fixed, then regressed, then fixed... again and again.  Such is the pain of being forced to use old protocols.

We can, however use a program called "Ubuntu Mainline Kernel Installer".

UMKI allows on to quite trivially download alternative kernels and install them with zero skill. 

I am using it, but it comes with a dire warning that **Here Be Dragons** and it might cause you.... problems.

To the Kernel.org link above, I have tried the suggested 6.0.15, 6.1.8 and 6.1.11 - all without luck.  I will try others, such as 5.15 and older, as this bu reared its ugly head around Christmas time (if memory serves me correctly).  If I find one that works, I shall write here with an update.

SO! There is the pay-off - one has to balance the desire to fix a SAMBA 1.0 bug, or lose some capability/support/features with an unofficially supported Kernel for their DE.... (I'm willing to risk it).

**Comment by blackmyre** [comment]
Yep, I can confirm the problem has come back for me too, also Mint 21.1 with kernel 5.15.0-60. 

> the inability to kill the pop-up

I found that xkill seems to get rid of that, though I haven't checked whether it leaves processes hanging.

Thanks for posting this, it was interesting to read the details and some of the thread in the kernel discussions. Like some of the contributors to that thread I'm disappointed that the code is being completely removed instead of retaining it behind kernel options. In my case the affected device is a Western Digital MyBookLive NAS. I bought it new 10 years ago so yeah, it's old, but not exactly a museum piece - its last update was in 2015, making it much more recent that some of the stuff that is still supported. 

The MyBookLive hasn't put a foot wrong and is still working just fine but I'm giving up. I'll be replacing it with a small form factor PC that's only slightly more recent but much more open. I'll either make a project of trying to install something else on the MyBookLive or perhaps use it as a secondary archive for non-GUI use.

**Comment by icebreaker-ch** [comment]
Same problem here on Linux Mint LMDE 6 Faye with kernel 6.1.0-17-amd64 (see system configuration attachment).
Copying the same file by command-line, double-commander or with other file managers works, but nemo fails, so this can not
be a problem of cifs or any other component.
This is a serious problem, which has to be solved with priority.
[sysinfo.txt](https://github.com/linuxmint/nemo/files/14078132/sysinfo.txt)

**Comment by luc77** [comment]
I think I have found a solution that at least works well for the kernels that came with distro Linux Mint 21.x
Don't know if it will work for others...

mounting a cifs at fstab it must have a 'cache=loose' and all started to work just fine.

my fstab cifs mount now looks like this now:
//192.168.0.250/ServerFolder /home/Whatever_local_folder cifs rw,noexec,cache=loose,user=xxxxx,pass=yyyyy,uid=myself,gid=myself,file_mode=0777,dir_mode=0777 0 0

[ replace  the obvious stuff with your own stuff :) ]

Would be nice to hear successes on other distros kernels etc. 
lc.

**Comment by icebreaker-ch** [comment]
@luc77: Unfortunately, your solution did not work for me.
I found, the problem indeed seems to be a kernel problem (see attached logfile `[dmesg.txt](https://github.com/linuxmint/nemo/files/14088676/dmesg.txt)`).
The workaround for me was, to go back from kernel `linux-image-6.1.0-17-amd64` to `linux-image-6.1.0-16-amd64`.
With the older kernel, I had no problems copying/pasting files with nemo.

**Comment by luc77** [comment]
@icebreaker-ch : No doubt in my mind that this is, and always have been, a kernel issue. It comes and goes in a way beyond my understanding. At the kernels 4.x some of them had issues others did not and all times I had the problem going back to kernel 4.11.0 solved it (as it did for many others) later it work well on some 5.x versions and on others it did not, and now on 6.x seems to be the same. The saga continues...
Specifically on the 5.15.0 I discovered that cache=loose solved it too. But I don't believe, not even for a second, that I have discovered any final solution. (well... it is just another weird discovery into the mix).
I pretty sure that this issue will keep coming and going depending on the wind direction.
