### ISSUE TITLE
Permissions clarification

### ISSUE THREAD

**Issue by jbergengh** [linuxmint/nemo#2206]
```
 * Nemo version 4.2.3
 * Is issue with desktop or windowed nemo? windowed
 * Distribution - Mint 19.2
 * Graphics hardware *and* driver used: Intel
 * 64 bit
 ```

File permissions for "Others" not identified

Open Nemo
Right Click on any file, such as a jpeg for example
Select "Properties"
Select the "Permissions" tab
Nemo displays the "Owner" and their access level, the Group and their access level, followed by another Access level which is not identified.  This second access level should be identified as "Others"

Two Access levels are shown under "Group".  One should be identified as Group and the other should be identified as "Others"

Clarification only.  Not a bug.

**Comment by smurphos** [comment]
Can you screenshot what you are seeing....Others is present and correct here...

![screenshot-window-2019-09-17-060209](https://user-images.githubusercontent.com/29017677/65012856-c3408380-d910-11e9-8039-229474e9eae9.png)

**Comment by jbergengh** [comment]
![Screenshot from 2019-09-16 11-02-47](https://user-images.githubusercontent.com/55407804/65052090-dfe3b800-d91e-11e9-8603-14933189e258.jpg)

**Comment by smurphos** [comment]
Yep your right that GUI should be fixed. BTW - thie first GUI in my post is the Advanced Permissions view. It can be enabled via Nemo preferences.

![screenshot-window-2019-09-18-074940](https://user-images.githubusercontent.com/29017677/65122596-47663a00-d9e9-11e9-96f0-92adbd37037e.png)

**Comment by jbergengh** [comment]
It's been over 6 years and this trivial correction hasn't been made.  It still exists in Nemo 6.6.3
