### ISSUE TITLE
Why does "Apply Permissions to Enclosed Files" button not work?

### ISSUE THREAD

**Issue by TheUnhappyUser** [linuxmint/nemo#2460]
```
 * Nemo version 4.4.2
 * Is issue with desktop or windowed nemo -- What does this actually mean?????
 * Distribution - (Mint 18.3, Cinnamon)
 * Graphics hardware *and* driver used -- NVIDIA GF114 [GeForce GTX 560 Ti] driver: nouveau v
 * 64 bit
 ```

**Issue**
"Apply Permissions to Enclosed Files" button still does not work.

Issue was raised in "Improve user rights and ownership management #1100" by  joe-13 on Feb 20, 2016

Later that year xenopeek commented on Aug 25, 2016 that "there is a button to apply the permissions of a directory to the enclosed files."

Two years later, gabrielfern commented on Oct 19, 2018 that "the button does not work @xenopeek (not even to change only permissions to enclosed ones)"

icarter09 for some reason added the "FEATURE REQUEST" label on Jan 20 (2020?) and then, as if the issue was magically fixed, he then closed the issue one day later on Jan 21

Why was this a "FEATURE REQUEST"? Was this not an issue with the fact that the button does NOT do what it says it is going to do?

icarter09 obviously did not even check the operation of this button! It does NOT even do what the label says it would do!

Why has it NOT been fixed in 4+ years? If you do not want to fix it, then remove button so people do not keep finding that it does NOT work!!!!

**Steps to reproduce**
1. Highlight file/directory
2. Right Click on "Properties"
3. Click on "Permissions"
4. Click on "Apply Permissions to Enclosed Files" button
5. No obvious action performed.
6. Check permissions of files in directory structure, and NOTHING has been changed!
7. End up making the needed owner and group changes in terminal.
8. Wonder why it was necessary to use chown when the button supposedly will make the changes.

**Expected behaviour**
Permissions on files in that directory would actually be changed.

**Other information**

**Comment by xenopeek** [comment]
It's fixed in newer versions of Nemo. The fix won't be backported to the Nemo version on Linux Mint 18.3. Consider upgrading to a newer Linux Mint version.

Testing the same on Linux Mint 20 just now, assuming you made some change to permissions between steps 3 and 4, the apply permissions to enclosed files button applies the permissions changes to the directory itself and to all contained directories and files (any depth).

**Comment by joe-mint** [comment]
Not fixed. I've just written a new issue, because it still doesn't work on my new mint 20 system!
Exactly the same behavior as (years) before...
