### ISSUE TITLE
Folder navigation is slow

### ISSUE THREAD

**Issue by gdevenyi** [linuxmint/nemo#310]
In Nemo, double clicking on a folder to go down a level in the directory structure results in a significant and noticeable pause (1-3 seconds) when compared to Nautilus which is nearly instantaneous.

This is on Ubuntu 13.04

nemo --version
nemo 1.8.1

Cinnamon/nemo installed from deb http://ppa.launchpad.net/gwendal-lebihan-dev/cinnamon-stable/ubuntu raring main

**Comment by Howaner** [comment]
The folder switch is still slow ...
Windows explorer, nautilus and caja are faster than nemo ...

**Comment by theajr** [comment]
Pressing Esc Key each time is not a good solution.. can anybody fixed in some other way? let me know if you do?

**Comment by acpadhi** [comment]
yes, noticed the same here this side too. Ubuntu 14.04, Nemo 2.8.7

Pressing escape improves, but still does not make it as fast as Nautilus, but there are improvements. Eager to know what does escape do while a folder is waiting to be loaded. I am thinking, the delays are more evident when moving away from very folder with large number of files to a folder with lesser number of files. So may be escape does something while moving out of a folder with very large number of files.
