### ISSUE TITLE
Moving files from Trash subfolders has no effect, or causes the progress window to hang

### ISSUE THREAD

**Issue by IfGremlinThen** [linuxmint/nemo#3286]
### Distribution

Mint 21.2

### Package version

5.8.4

### Frequency

Quite often

### Bug description

Pretty simple, if I have a folder in the Trash, and that folder contains any files, like a small .mp3 or .txt, and I attempt to drag-and-drop one of those files from that folder to the Desktop (or any other folder), I get the "Moving 1 item" progress window, but it doesn't progress and the process never completes.

Clicking the stopsign icon only greys it out and nothing ever happens.  If I Close out of the progress window and attempt the action again, the same thing happens, and then I'll have 2 separate pending processes which Linux Mint will warn is preventing it from shutting down or restarting if you attempt to do so.

I have to select "End Process" on the `nemo-desktop` in the task manager to clear these processes.

Attempting to right-click and Copy a file from a Trash subfolder will have no apparent effect when you right-click and Paste to a destination folder.

### Steps to reproduce

Put a .txt in a folder.
Trash the folder.
Drag-and-drop the .txt to new folder outside of the Trash.

All of this is after a very recent install of Mint 21.2.

### Expected behavior

Just responsive drag-and-drop.

### Additional information

Running `nemo --quit && nemo` only results in:

```
Called "net usershare info" but it failed: 'net usershare' returned error 255: net usershare: cannot open usershare directory /var/lib/samba/usershares. Error No such file or directory
Please ask your system administrator to enable user sharing.
```

**Comment by leigh123linux** [comment]
Trash is a gvfs file system, you need to restore the complete folder.

**Comment by IfGremlinThen** [comment]
What, so it's my fault if Nemo just decides to hang a process a window and fail to shutdown properly?

**Comment by mtwebster** [comment]
I'm pretty certain this is related to:
https://github.com/linuxmint/nemo/issues/3285
https://github.com/linuxmint/nemo/issues/3266
https://github.com/linuxmint/nemo/issues/3271

and has been fixed already, just waiting on an update.
https://github.com/linuxmint/nemo/commit/c64905efd219a4da64846e600ebd1f4ed0583131

**Comment by IfGremlinThen** [comment]
Big if true.

**Comment by yumashka** [comment]
> I'm pretty certain this is related to: #3285 #3266 #3271
> 
> and has been fixed already, just waiting on an update. [c64905e](https://github.com/linuxmint/nemo/commit/c64905efd219a4da64846e600ebd1f4ed0583131)

It is not. 
I have rebuilded nemo with this fix. Incorrect Type=Link behaviour has been fixed. But this issue remains unfixed.
