### ISSUE TITLE
Rename bookmarks

### ISSUE THREAD

**Issue by Wolfgang-MK** [linuxmint/nemo#3519]
### Distribution

Mint 22.1 Cinnamon

### Package version

NEMO 6.4.3

### Frequency

Always

### Bug description

In the current file manager NEMO 6.4.3, bookmarks can be created, but they can no longer be renamed in the context menu (right mouse button). Unfortunately, this is only possible with Bookmarks/Edit Bookmarks or CTRL-B

### Steps to reproduce

Create bookmark + select with right mouse button + rename = is no longer possible

### Expected behavior

Renaming is offered, but the field for renaming no longer appears

### Additional information

Unfortunately Renaming is only possible with Bookmarks/Edit Bookmarks - oder mit Control-B

**Comment by MerQury14092** [comment]
the developers have already [fixed](https://github.com/linuxmint/nemo/commit/c51a8e5ff32a11f6feff6e44c06f4f12ffa4bd92) this problem, wait for the next distribution of the program

**Comment by leigh123linux** [comment]
Fixed in https://github.com/linuxmint/nemo/commit/c51a8e5ff32a11f6feff6e44c06f4f12ffa4bd92

**Comment by Wolfgang-MK** [comment]
nemo has not been fixed yet. The error still exists. Status: February 14, 2025

**Comment by titojff** [comment]
Fixed by  
 [ Michael Webster ]
   * nemo-places-sidebar.c: Remove delete key action for removing bookmarks.
   * nemo-places-sidebar.c: Fix bookmark renaming.
