### ISSUE TITLE
100% utilization of a CPU core, constant disk activity, memory leak

### ISSUE THREAD

**Issue by anushr** [linuxmint/nemo#671]
Version: Linux Mint 17, Cinnamon 64-bit

System model: Lenovo T520

What you did for the problem to happen: I upgraded (fresh install) from Mint 15 to 17

What happened: The nemo process appears to always be at 20-25% CPU usage (1 CPU core) and my hard disk is constantly "working" (HDD light keeps flashing and I can hear it). If I kill the nemo process, the HDD immediately goes quiet. If I open up nemo again, it's back to 20-25% CPU and a constantly working HDD. I tried leaving it running for 2-3 hours and it gobbled up 2+ gigs of memory.

Also reported on Linux Mint: https://bugs.launchpad.net/linuxmint/+bug/1326318

![Screenshot from top](https://cloud.githubusercontent.com/assets/109667/3779365/305da542-1981-11e4-87c2-84d4a78f4eb5.png)

**Comment by patadejaguar** [comment]
Hi boys,
I have a PC Ubuntu Cinnamon with nemo 2.4.4. nemo eat my memory without opened files.
![captura de pantalla de 2015-04-14 15 52 45](https://cloud.githubusercontent.com/assets/370248/7147296/8f9825e8-e2bf-11e4-8179-b56842b10ea1.png)

**Comment by KAMI911** [comment]
Leaking Nemo after more than one day runtime:
http://pastebin.com/WFJyi7S0

Nemo opening several non existing files:
http://ooo.itc.hu/linuxmint/nemostrace.txt

**Comment by KAMI911** [comment]
I found a workaround, just disable: Other Previewable Files in Nemo -> Settings -> Preview and the CPU usage goes to normal level.

**Comment by gregsheremeta** [comment]
Still an issue in nemo 2.8

strace whines about missing files related to thumbnails

nemo-2.8.6-1.fc23.x86_64

**Comment by Vahan86** [comment]
@anushr, is this still an issue for you with Nemo 3.0.6?

**Comment by anushr** [comment]
@Vahan86 I don't use nemo anymore, so can't really validate the issue.

Maybe one of the other reporters can chime in? @tiktaz @Ryuzaki11 @mc0e @jfmoulin @gregsheremeta

**Comment by KAMI911** [comment]
Reenabled the preview option. It uses CPU but seems normal. Wait few days and I will report back related to memory usage.

**Comment by gregsheremeta** [comment]
I haven't seem any leaks or otherwise bad behavior  in nemo 3.0.6!

$ rpm -q nemo
nemo-3.0.6-1.fc24.x86_64

**Comment by atorg** [comment]
I'm having what I believe is the same issue on a fresh install of LM Cinnamon 18.
In my case Nemo immediately uses ~600MB when I open a file browser.
This happens reliably every time.
Response to commands is extremely sluggish in the filebrowser.
In an strace I repeatedly get these lines, which seems perhaps not right:

`access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)`

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a bug?

**Comment by leigh123linux** [comment]
I believe the original thumbnail issue was fixed.
As for the other users complaining about various extensions, they can refile there issues nemo-extensions.

https://github.com/linuxmint/nemo-extensions

**Comment by mritunjaymusale** [comment]
Mint 19.1 can confirm it's still happening it consumed like 4.5 gb in the background while I was playing a game, 2 of my cores were pinned to 100% in the system monitor I killed the process and it restarted all by itself again and it continued to the do the same. The only way I was able to stop it for now, is by setting it as low priority then killing it

**Comment by lolmaus** [comment]
Nemo 4.4.2 using 100% of a CPU core for me on Linux Mint 19.3 Cinnamon.

It gets CPU temperature to 100, causing CPU to throttle.

**Comment by RunkelRitter** [comment]
In my case Nemo 4.6.5 in Mint 20.04 Ulyana Cinnamon still uses 100% of a core when using image preview.
